# This file was generated by GoReleaser. DO NOT EDIT.
cask "s3lock" do
  name "s3lock"
  desc "s3lock is a locking command using S3."
  homepage "https://github.com/winebarrel/s3lock"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3lock"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_darwin_amd64.tar.gz"
      sha256 "312ab7e6893696e00a728332edfceff0d266ddd6d0f90a63cc56c4093cfdf5fd"
    end
    on_arm do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_darwin_arm64.tar.gz"
      sha256 "a4d8bb3de6614249364c75b6137ef6fe61650e733218a17dac8c74882846acb0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_linux_amd64.tar.gz"
      sha256 "eae755a0423055df8a4a2f9b6340d7f54320609409d215417d0b63521427a053"
    end
    on_arm do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_linux_arm64.tar.gz"
      sha256 "af8b0bfad5e23326f045484d82810eab1dc05e7cc62174f84e7048f8d85d8b2d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s3lock"]
    end
  end

  # No zap stanza required
end
