# This file was generated by GoReleaser. DO NOT EDIT.
cask "s3lock" do
  name "s3lock"
  desc "s3lock is a locking command using S3."
  homepage "https://github.com/winebarrel/s3lock"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3lock"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_darwin_amd64.tar.gz"
      sha256 "0f5bef029d109d6bd9615bba195f8e9ca427f13d556827cb1a6b769e6486054d"
    end
    on_arm do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_darwin_arm64.tar.gz"
      sha256 "96c9c1fee54bf8d7b9b5aaab3268078824d079cfbb798eb9f229f4b7ffa2f32b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_linux_amd64.tar.gz"
      sha256 "a30919a5641d7ca5c5ee3716de5c164441f17a70ecadb62ef9f9b3fe9e5cf1be"
    end
    on_arm do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_linux_arm64.tar.gz"
      sha256 "b6cf02bc74483ff3ae93223e51b7cfcc7662aa6287e23f7656d579329d2d5451"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s3lock"]
    end
  end

  # No zap stanza required
end
