# This file was generated by GoReleaser. DO NOT EDIT.
cask "s3lock" do
  name "s3lock"
  desc "s3lock is a locking command using S3."
  homepage "https://github.com/winebarrel/s3lock"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3lock"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_darwin_amd64.tar.gz"
      sha256 "c35c50024682688df41e1fd1a879d1a857c10354e9a5973ad7c83b3aa5d177c3"
    end
    on_arm do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_darwin_arm64.tar.gz"
      sha256 "373cbbb4e326535f6111c24468bb3c23164bad5f0fa6832ad21bce9c2223884e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_linux_amd64.tar.gz"
      sha256 "efddf96c5960495e2cd991a3ef0291a564838784875c1d86c95b41b173f84cee"
    end
    on_arm do
      url "https://github.com/winebarrel/s3lock/releases/download/v#{version}/s3lock_#{version}_linux_arm64.tar.gz"
      sha256 "92bcdfd6b5fddd982f150bd22b9c9ef15a23539167211e12b13ada117db8078d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s3lock"]
    end
  end

  # No zap stanza required
end
